# Configuration site theme
theme:
  name: material
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: './images/logo-theeye-circle.png'
  favicon: './images/logo-theeye-docu-glasses.png'

# Project information
site_name: 'TheEye'
site_description: 'TheEye is a platform for Robot automation Processes and Systems'
site_url: 'https://app.theeye.io/dashboard'

# Menu
nav:
- Home: 'index.md'
- Core concepts:
    - 'What is TheEye?': './core-concepts/the-eye.md'
    - 'Resources': './core-concepts/resources.md'
- First steps:
    - 'Organization': 'index.md'
    - 'Bot Installation': 'index.md'
- User management:
    - 'User Accounts and Roles': './user-management/index.md'
    - 'ACLS': './user-management/acls.md'
    - 'Managing users': './user-management/managing-users.md'
    - 'Permission profiles': './user-management/permission-profiles.md'
- Resources:
    - 'Indicators': './resources/indicators.md'
    - 'Monitors': './resources/monitors.md'
    - 'Tasks':
        - 'Tasks': './resources/tasks/index.md'
        - Workflows:
            - 'Connecting tasks': './resources/tasks/workflows/index.md'
            - 'Tasks with CLI': './resources/tasks/workflows/cli-util.md'
            - 'Alerts and Notifications': './resources/tasks/workflows/alerts-and-notifications.md'
    - 'Templates': './resources/templates.md'
    - 'Webhooks': './resources/webhooks.md'
    - 'Scripts':
        - 'Scripting with theeye': './resources/scripts/index.md'
        - 'Run as...': './resources/scripts/runas.md'
        - 'Write': './resources/scripts/write.md'
- Integrations:
    - 'AWS': './integrations/aws-EC2.md'
    - 'ELK': './integrations/elk-Data-Injection.md'
    - 'Kubernetes': './integrations/kubernetes.md'
    - 'API for developers': './integrations/run_tasks_via_api.md'
- Assets:
    - TheEye agent:
        - 'Installation': './assets/the-eye-agent/index.md'
        - 'Binary build': './assets/the-eye-agent/binary_build.md'
        - 'Setup': './assets/the-eye-agent/setup.md'
        - 'Debug': './assets/the-eye-agent/debug.md'
        - 'Raspberry': './assets/the-eye-agent/raspberry.md'
        - 'Services in Linux':
            - 'Example init.d': './assets/the-eye-agent/examples/etc_init.d_theeye-agent'
            - 'Example systemd': './assets/the-eye-agent/examples/etc_systemd_system_theeye-agent.service'
    - Recipes:
        - 'indicatorExample.json': './assets/recipes/indicatorExample.json'
    - Scripts:
        - 'Example .bat': './assets/scripts/example.bat'
        - 'Example .go': './assets/scripts/example.go'
        - 'Example .js': './assets/scripts/example.js'
        - 'Example .php': './assets/scripts/example.php'
        - 'Example .pl': './assets/scripts/example.pl'
        - 'Example .ps1': './assets/scripts/example.ps1'
        - 'Example .sh': './assets/scripts/example.sh'
- Support: 'support.md'
- About:
    - 'About us': './about/index.md'
    - 'License': './about/license.md'
    - 'Summary': './about/summary.md'

# Footer
copyright: 'TheEye.io | Copyright &copy; 2019 - All rights reserved'
extra:
  social:
    - type: 'medium'
      link: 'https://medium.com/@theeye_io'
    - type: 'facebook'
      link: 'https://www.facebook.com/theeyeio/'
    - type: 'twitter'
      link: 'https://twitter.com/theeye_io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/theeye.io/'

